const errors = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_VALIDATION_ERROR: "USER_VALIDATION_ERROR",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

    TEAM_VALIDATION_ERROR: "TEAM_VALIDATION_ERROR",
    
    PLAYER_VALIDATION_ERROR: "PLAYER_VALIDATION_ERROR",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",

    TRANSFER_VALIDATION_ERROR: "TRANSFER_VALIDATION_ERROR"
}

export default errors